#! /usr/bin/env bash

echo "Are you absolutely sure? [the operation deletes all statistics] (yes/no)"
read r
if [ "$r" == "yes" ]; then
	cd htdocs/
	rm statistics/*
	rm logs/*
	7za a -up1q1r2x1y1z1w1 archive/gondolas.zip video sources
fi

