#! /usr/bin/env bash

echo "(Re)build image? (y/n): "
read answer
if [ "$answer" = y ]; then
	docker build . -t gondola-archive
fi

docker run --rm -e HOST_UID=$UID -e HOST_PASS='nani sore desu ka' -v $HOME/stuf:/home/user/stuf -v $(pwd):/home/user/racket -p 8002:8000 gondola-archive
